### ISSUE TITLE
Export jadi gambar

### ISSUE THREAD

**Issue by Thaza-Kun** [samudradev/samudra#4]
Export maklumat lemma, maksud2nya serta metadata terpilih menjadi gambar supaya mudah dikongsi ke tempat lain.

**Comment by afiqzx** [comment]
Boleh guna ffmpeg?
Nampaknya pembangunan agak aktif. Tapi, ffmpeg lebih berfokus kepada penyuntingan video. (Boleh juga digunakan untuk gambar)

**Comment by Thaza-Kun** [comment]
FFMPEG lebih menumpu ke arah video. Risau kalau ada banyak benda yang tidak diperlukan.

Pakej yg popular untuk imej dalam Python ialah [Pillow](https://pillow.readthedocs.io/en/stable/). Mungkin boleh tengok itu atau alternatif lain kalau tahu.

**Comment by Thaza-Kun** [comment]
Salam @afiqzx, boleh saya tahu perkembangan fitur ini? Adakah tuan sedang mengerjakannya atau tidak? Boleh tahu setakat mana sudah dibangunkan kalau ya?

**Comment by afiqzx** [comment]
Maaf, saya sedang fokus pada projek sumber terbuka yang lain. Lagipun, saya sedang berehat sekarang kerana dapat covid-19.

**Comment by Thaza-Kun** [comment]
Baiklah. Terima kasih atas makluman. Nanti bolehlah maklumkan jika sudah bersedia mahu bangunkan fitur ini sementara saya tumpu ke bahagian lain.
