### ISSUE TITLE
Kumpulkan data semu untuk bangunkan model

### ISSUE THREAD

**Issue by Thaza-Kun** [samudradev/samudra#6]
Supaya ada data dari kamus sedia ada yang boleh kita guna untuk kembangkan model (bukan untuk ambil data mereka ke dalam pangkalan data kita)

**Comment by SyafiqHadzir** [comment]
Kesemua data ini boleh diambil dari https://github.com/hikayatmelayu/pangkalan-data-raya dan https://github.com/hikayatmelayu/manuscript-corpus
